### ISSUE TITLE
Error: failed to start container "snapscheduler": Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by tomdymond** [backube/snapscheduler#118]
I'm trying to run this in eks with version 1.17 but I get the following error: 

```
kubectl describe po/snapscheduler-864d84f9-gnzwb -n snapscheduler

Events:
  Type     Reason     Age                 From                                                Message
  ----     ------     ----                ----                                                -------
  Normal   Scheduled  <unknown>           default-scheduler                                   Successfully assigned snapscheduler/snapscheduler-864d84f9-gnzwb to ip-10-27-7-136.eu-west-2.compute.internal
  Normal   Pulled     23m (x5 over 25m)   kubelet, ip-10-27-7-136.eu-west-2.compute.internal  Container image "quay.io/backube/snapscheduler:1.1.1" already present on machine
  Normal   Created    23m (x5 over 25m)   kubelet, ip-10-27-7-136.eu-west-2.compute.internal  Created container snapscheduler
  Warning  Failed     23m (x5 over 25m)   kubelet, ip-10-27-7-136.eu-west-2.compute.internal  Error: failed to start container "snapscheduler": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/manager\": stat /manager: no such file or directory": unknown
  Warning  BackOff    7s (x112 over 24m)  kubelet, ip-10-27-7-136.eu-west-2.compute.internal  Back-off restarting failed container
```

Using the following HelmRelease

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snapscheduler
  namespace: fluxcd
  annotations:
    flux.weave.works/automated: "false"
spec:
  targetNamespace: snapscheduler
  helmVersion: v3
  releaseName: snapscheduler
  chart:
    repository: ***
    name: snapscheduler
    version: 1.2.1
  values:
    replicaCount: 2

    image:
      repository: quay.io/backube/snapscheduler
      tagOverride: ""
      pullPolicy: IfNotPresent

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    serviceAccount:
      create: true

    podSecurityContext: {}
    securityContext: {}
    resources:
      requests:
        cpu: 10m
        memory: 100Mi

    nodeSelector:
    tolerations: []
    affinity: {}

```
