### ISSUE TITLE
Snapshot metrics

### ISSUE THREAD

**Issue by JohnStrunk** [backube/snapscheduler#121]
**Describe the feature you'd like to have.**
Currently, snapscheduler doesn't provide any metrics related to the snapshots attempted/created. It would be good to provide some stats that could be monitored/alerted

**What is the value to the end user? (why is it a priority?)**
Users that depend on having snapshots to protect their data should have a way to monitor whether those snapshots are being successfully created

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**
cc: @prasanjit-enginprogam

**Comment by prasanjit-enginprogam** [comment]
Here are the additional stats that we are requesting for: 

1)  **readyToUse** boolean flag based on 
         - SnapshotSchedule Name
         - Match Lables
         - Namespaces
         - VolumeSnapshotClass
2) current count of snapshot per PVC, so that team can get alerted if it reaches  the **maxCount** number present in SnapshotSchedule.yaml (Kind: SnapshotSchedule), based on 
          - SnapshotSchedule Name
         - Match Lables
         - Namespaces
         - VolumeSnapshotClass      
3) Current count of **count/volumesnapshots.snapshot.storage.k8s.io** based on namespace. 


our HELM CHART BASED YAML FILES ARE

**snapschedule.yaml**
```
apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: consul-snapshot
  namespace: {{ .Values.namespace }}
spec:
  disabled: {{ .Values.snapshotDisabledFlag }}
  claimSelector:
    matchLabels:
      {{- range $key, $value := .Values.selector }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
  retention:
    expires: {{ .Values.snapshotExpiry }}
    maxCount: {{ .Values.maxCount }}
  schedule: {{ .Values.schedule }}
  snapshotTemplate:
    lables:
      {{- range $key, $value := .Values.selector }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    snapshotClassName: {{ .Values.snapshotClassName }}
```
**snapshotquota.yaml**
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: volumesnapshotsquota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    count/volumesnapshots.snapshot.storage.k8s.io: {{ .Values.snapshotQuota | quote }}
```
