### ISSUE TITLE
Add non-namespaced SnapshotSchedules

### ISSUE THREAD

**Issue by timstoop** [backube/snapscheduler#181]
**Describe the feature you'd like to have.**
I would like to be able to deploy a single (or several) SnapshotSchedules cluster wide and have them operate on all namespaces. In most cases that we see, it makes more sense to make a single SnapshotSchedule available cluster-wide and use labels (or possible annotations) to have them applied to PVCs.

**What is the value to the end user? (why is it a priority?)**
Easier to add existing snapshot schedules when you prefer spreading out your applications over multiple namespaces. Also easier to have a single "enforced" snapshot schedule that should be adhered to. Or to change a schedule if it is warranted.

**How will we know we have a good solution? (acceptance criteria)**
When a snapshot schedule only needs to be defined once on a cluster.

**Additional context**
I would recommend calling it something like ClusterSnapshotSchedule, in line with upstream resources like Role and ClusterRole or resources provided by commonly used third parties, like Issuer and ClusterIssuer.

**Comment by bo0tzz** [comment]
I'd like to have this option as well. My usecase specifically would be to apply a schedule indiscriminately to all PVCs of a certain StorageClass.

**Comment by nikkischnelle** [comment]
for anyone coming across this now: i've worked around this using a kyverno GeneratingPolicy that clones all snapshotschedules from the `backube-snapscheduler` into all other namespaces
<details>
  <summary>GeneratingPolicy</summary>
  
  ```yaml
  ---
  apiVersion: policies.kyverno.io/v1
  kind: GeneratingPolicy
  metadata:
    name: clone-all-snapshot-schedules
  spec:
    evaluation:
      generateExisting:
        enabled: true
      synchronize:
        enabled: true
    matchConstraints:
      resourceRules:
        - apiGroups: ['']
          apiVersions: ['v1']
          operations: ['CREATE', 'UPDATE']
          resources: ['namespaces']
    matchConditions:
      - name: exclude-system-namespaces
        expression: "!(object.metadata.name in ['kube-system', 'cilium-secrets'])"
    variables:
      - name: nsName
        expression: 'object.metadata.name'
      - name: sourceSchedules
        expression: resource.List("snapscheduler.backube/v1", "snapshotschedules", "backube-snapscheduler")
    generate:
      - expression: generator.Apply(variables.nsName, [variables.sourceSchedules])
  ```
</details>
<details>
  <summary>necessary ClusterRole</summary>

  ```yaml
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: kyverno-snapscheduler-permissions
    labels:
      rbac.kyverno.io/aggregate-to-background-controller: "true"
      rbac.kyverno.io/aggregate-to-admission-controller: "true"
  rules:
    - apiGroups: ["snapscheduler.backube"]
      resources: ["snapshotschedules"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  ```
</details>
