### ISSUE TITLE
Regex evaluating cron is too restrictive

### ISSUE THREAD

**Issue by wjentner** [backube/snapscheduler#229]
**Describe the bug**

The regex to evaluate a correct cron is currently:
```
^((\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}|@(hourly|daily|weekly|monthly|yearly))$
```
This is IMHO too restrictive as it does not allow for crons such as:
```
0 0,6,12,18 * * *
```
(create every 6 hours)

I've patched my CRD manually with:
```
^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})$
```
(slightly adapted from https://stackoverflow.com/a/57639657/1986417)

The lib that evaluates the cron is https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc
It is statet in the docs that such crons are accepted.

Since my manual patch of the CRD, I have had no issues.

**Steps to reproduce**

```yaml
apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: test
spec:
  retention:
    maxCount: 6
  schedule: 0 0,6,12,18 * * *
```

fails (because of CRD evaluation)

**Expected behavior**

Should be possible since it is valid cron syntax.

**Actual results**

**Additional context**

If my regex is okay for you, I'm happy to submit a PR.

**Comment by JohnStrunk** [comment]
Happy to have a PR that adds ranges (x-y) and commas to the permitted syntax. I don't think the `@every` intervals will work with how the package is currently being used for scheduling, but I could be wrong.

**Comment by wjentner** [comment]
I just tested the `@every` syntax:

```yaml
apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: test-every
spec:
  retention:
    maxCount: 6
  schedule: '@every 5m'
status:
  conditions:
    - lastHeartbeatTime: '2022-09-21T00:18:29Z'
      lastTransitionTime: '2022-09-21T00:06:15Z'
      message: Reconcile complete
      reason: ReconcileComplete
      status: 'True'
      type: Reconciled
  nextSnapshotTime: '2022-09-21T00:23:29Z'
```

The `nextSnapshotTime` is continuously updating and always points to 5 minutes into the future.
So no snapshots are being created.
